### ISSUE TITLE
'Gtk.Application' threw an exception.

### ISSUE THREAD

**Issue by AngelJumbo** [area-of-dev/Pinta.AppImage#2]
I get this when I try to run this appimage:
`Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Pinta.MainClass.Main(String[] args)
fish: Job 1, 'pinta' terminated by signal SIGABRT (Abort)
`

**Comment by AlexWoroschilow** [comment]
which system are you working with? it looks like the libgtk3 is not installed

**Comment by AngelJumbo** [comment]
I use void linux and I already have the libgtk3(in void is called gtk+3) installed.
